### ISSUE TITLE
Loss nan when "--minibatch True"

### ISSUE THREAD

**Issue by wenruij** [AYLIEN/gan-intro#1]
hi @johnglover 
    It's well to run `python gan.py`
    But i got all **nan** for loss when running with minibatch discrimination `python gan.py --minibatch True`:

```
0: inf  nan
10: nan nan
20: nan nan
30: nan nan
40: nan nan
50: nan nan
60: nan nan
70: nan nan
80: nan nan
90: nan nan
100: nan    nan
110: nan    nan
120: nan    nan
130: nan    nan
140: nan    nan
150: nan    nan
160: nan    nan
170: nan    nan
180: nan    nan
190: nan    nan
200: nan    nan
......
```

My numpy, scipy, seaborn and tensorflow are all in the newest version.

Any tips about this nan?

**Comment by johnglover** [comment]
@wenruij Hmm, not sure. Can you try with the versions of numpy/scipy from the `requirements.txt` and with Tensorflow `0.8`?

**Comment by simplysimleprob** [comment]
I have an exactly same error. used the exact same versions of numpy/scipy with Tensorflow 1.0

**Comment by abhishm** [comment]
I also got the same error with Tensflow 1.0.

**Comment by abhishm** [comment]
I finally found the problem. The problem lies in using `eps` variable when calculating the minibatches. After removing the `eps`, I was able to run the code as you described. 

I believe the `eps` variable were introduced for stability issues. When I removed it, the code is working fine.

**Comment by johnglover** [comment]
@abhishm Thanks, I'll have a look at this when I get a chance. Yes `eps` was indeed introduced for that reason (I actually took this from the implementation in https://github.com/openai/improved-gan), but maybe this is a bit problematic. Not sure why the version of TensorFlow should matter here though.

**Comment by ysjakking** [comment]
Hi, thanks for the work. Since I have not learned to use tensor flow yet,  I wonder if the mini-batch discriminator kernel (a.k.a., the tensor T  in the original paper) is trainable or not, or it is fixed during the whole training process ???

**Comment by johnglover** [comment]
@ysjakking: this is trainable.

**Comment by MalteFlender** [comment]
I am getting the same NaN error but I can't find anything named `eps` in the code.  
Can somebody provide any hints on what to change in order to make the code work?
