### ISSUE TITLE
Request for rewriting gan-intro codes in keras?

### ISSUE THREAD

**Issue by potholiday** [AYLIEN/gan-intro#4]
I came across this article http://blog.aylien.com/introduction-generative-adversarial-networks-code-tensorflow/ and I am impressed by how you used a toy example of 1-D gaussian distribution to explain GAN's. I myself is not well versed in TensorFlow and because of that I understood only a small parts in your tutorial. Can I request an article about implementation of this GAN code in keras with theano or tensorflow backend.

Thank you

**Comment by johnglover** [comment]
@potholiday Thanks, but I'm not going to rewrite this for different backends at the moment. If you have time though feel free and I'll add a link to the readme.
